@startuml



title NEOT Components

component [Sensor1] as S1
component [Sensor2] as S2
component [Sensor Delegate] as SD
component [Sensor3] as S3

cloud "Offchain P2P network" as Internet {
}
cloud Blockchain {
}

node "Sensor Node I" as NN1 {
    [Adapter1] as A1
    interface "NEOT Interface" as ProtNEOT1
    [NEP5] as NEP1
    [PROV1] as TN1
}
    
    

node "Sensor Node II" as NN2 {
    [Adapter2] as A2
    interface "NEOT Interface" as ProtNEOT2
    [NEP5] as NEP2
    [PROV2] as TN2
}
    

S1 -d- SD: Raw D/S
S2 -d- SD: Raw D/S
SD -d- A1: Raw D/S
A1 -r-( ProtNEOT1
TN1 -u- ProtNEOT1
TN1 -( NEP1


S3 -d- A2: Raw D/S
A2 -r-( ProtNEOT2
TN2 -u- ProtNEOT2
TN2 -( NEP2

database "Host" as SR1

node "Host Node" as NN3 {
    [Adapter3] as A3
    interface "NEOT Interface" as ProtNEOT3
    [PROV3] as TN3
    [NEP5] as NEP3
}



SR1 -d- A3: Raw D/S
A3 -r-( ProtNEOT3
TN3 -u- ProtNEOT3
TN3 -r-( NEP3

TN1 -down- Internet
TN2 -down- Internet
TN3 -down- Internet


NEP1 -down- Blockchain
NEP2 -down- Blockchain
NEP3 -down- Blockchain

node "User Node" as User {
    [PROV4] as TN4
    [NEP5] as NEP4
}
TN4 -r-( NEP4

TN4 -up- Internet
NEP4 -up- Blockchain

@enduml