@startuml

skinparam componentStyle uml2

title NEOT Components

component [Sensor1] as S1
component [Sensor2] as S2
component [Sensor Delegate] as SD
component [Sensor3] as S3

cloud Internet {
}
cloud Blockchain {
}

node "Sensor Node I" as NN1 {
    [Adapter1] as A1
    interface "NEOT D/S Standard" as ProtNEOT1
    interface "NEP-5" as NEP1
    [Tunneo] as TN1
    interface "PDNE" as PDNE1
}
    
    

node "Sensor Node II" as NN2 {
    [Adapter2] as A2
    interface "NEOT D/S Standard" as ProtNEOT2
    interface "NEP-5" as NEP2
    [Tunneo] as TN2
    interface "PDNE" as PDNE2
}
    

S1 -d- SD: Raw D/S
S2 -d- SD: Raw D/S
SD -d- A1: Raw D/S
A1 -r-( ProtNEOT1
TN1 -u- ProtNEOT1
TN1 -d-( PDNE1
TN1 -( NEP1


S3 -d- A2: Raw D/S
A2 -r-( ProtNEOT2
TN2 -u- ProtNEOT2
TN2 -d-( PDNE2
TN2 -( NEP2

database "Host" as SR1

node "Host Node" as NN3 {
    [Adapter3] as A3
    interface "NEOT D/S Standard" as ProtNEOT3
    [Tunneo] as TN3
    interface "NEP-5" as NEP3
    interface "PDNE" as PDNE3
}



SR1 -d- A3: Raw D/S
A3 -r-( ProtNEOT3
TN3 -u- ProtNEOT3
TN3 -d-( PDNE3
TN3 -r-( NEP3

PDNE1 -down- Internet
PDNE2 -down- Internet
PDNE3 -down- Internet


NEP1 -down- Blockchain
NEP2 -down- Blockchain
NEP3 -down- Blockchain

@enduml