@startuml

title How it Works - An Example 

(*) --> ===BStart=== 
partition Manufacturer #CCCCEE{
    --> "Enable NEOT\n by developing Adapter\n for 'AwsSSD'"
    note right
    to develop Adapter,
    only standardized
    Data&Signal I/O
    is required
    end note
}

partition Provider {
    --> Buy AwsSSD1 
    note bottom
    Love NEOT powered
    devices, coz we don't
    need to research or 
    develop consumers 
    preferred services
    end note
    --> ===BManuDeploy===
    -->"Enable 'SrvRMTDisk' \non 'AwsSSD1'"
    note right
    Recognizes 
    SrvRMTDisk
    the most profitable
    end note
    
}

--> ===BService===

partition "PROV Indie DevA" #TECHNOLOGY{
    ===BStart=== --> "Develop service:\n 'SrvRMTDisk'"
    note top
    DevA makes the
    best balance between
    Consumer/Provider
    end note
}

--> ===BDev=== 
--> ===BManuDeploy===
===BStart=== --> "Other devs:\n 'OtherRMTDisk' services"
--> ===BDev=== 



partition Consumer #LightSkyBlue{
    ===BDev===  --> "Start Instance\n'SrvRMTDisk1'\n on NEOT node"
    note top
    Go host my
    pics for 1yr.
    end note
}
--> ===BService===
--> "PROV auto-picks\nAwsSSD1 as provider"
note top
    Consumers don't
    need to know who's
    provider
end note
--> "AwsSSD1 finished\n SrvRMTDisk1"
--> ===BSuccess===

partition Provider #TAN{
    ===BSuccess=== --> Earn Service Fee
}
partition "PROV Indie DevA" {
    ===BSuccess=== --> Earn royalty
}

===BSuccess=== --> (*)

@enduml