@startuml

title Value Flow
top to bottom direction
actor TermOwner as "Provider"
actor AdaDev as "Adapter Dev (Manufacturer)"
actor SerDev as "PDNE Developer"
actor User as "Consumer"

usecase NEOT as "Sensor Node | Nest Node" <<NEOT Node>>
usecase Service as "Service instance" << PDNE Service>>


AdaDev -left-> NEOT: Develop adapters
TermOwner -> AdaDev: Purchase devices
SerDev -> Service: Develop services

Service -right-> SerDev: Royalty
NEOT -> Service: Resource
NEOT -left..> TermOwner: Ownership
Service -up-> TermOwner: Service Fee
Service -left-> User: Service
User -> Service: Fee


@enduml